spring:
  application:
    name: birdex
  datasource:
    url: jdbc:postgresql://127.0.0.1:5455/birdex
    username: admin
    password: ""
    # driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  address: 0.0.0.0
  port: 8080

logging:
  level:
    root: INFO

birdnet:
  api:
    base-url: http://localhost:8000
    timeout-seconds: 60

birdex:
  thumbs:
    enabled: true

minio:
  access-key: minioadmin
  secret-key: minioadmin
  region: us-west-2
  bucket: birdex-bucket
  endpoint: http://localhost:9100
  birds:
    bucket: birds
    profile-object-name: profile

